opt_in_rules: # some rules are only opt-in
  - empty_count
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - switch_case_alignment
  - nesting
  - line_length
identifier_name:
  excluded:
    - id
