disabled_rules: # rule identifiers to exclude from running
#  - line_length
#  - trailing_whitespace
#  - block_based_kvo

line_length: 140

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - vc

#file_name:
#  excluded: ["ServerResponseObjects.swift", "NetworkHandlerProtocols.swift"]

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - target
  - build
  - DerivedData
