child_config: .swiftlint_refinement.yml

# Find all the available rules by running: `swiftlint rules`
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count
  - force_unwrapping
  - convenience_type
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  - private_action
  - private_outlet
  - toggle_bool

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - switch_case_alignment

force_unwrapping: error
